Backend for simple blast prototype
JStinenbosch/SteneGene pull request #4
Opened 2017-10-12 20:32 UTC by JStinenbosch

2017-10-15 12:54 UTC, FrankTN reviewed
We should still add some documentation in the more complicated functions, other than that it looks good

2017-10-15 12:54 UTC, FrankTN commented on PythonFiles/Blast.py
>      def make_blast_db(wgseqs, arguments):
We should also add a way to specify the target path here. This should be done in such a way that the blastquery function knows where the db's are.

2017-10-15 12:54 UTC, FrankTN commented on PythonFiles/BlastBuilder.py
> +        if seq_type is "N":
We can extract a function here to combine the behavior here with the behavior of set_WGS_flags

2017-10-16 10:11 UTC, jurrdb requested changes

2017-10-16 10:11 UTC, jurrdb commented on PythonFiles/Blast.py
> +        arg_string = add_property_to_string("seq_type", arguments, arg_string, "nucl")
revert seq_type to dbtype, since this is a blast argument.

2017-10-16 10:11 UTC, jurrdb commented on PythonFiles/BlastBuilder.py
> +        if seq_type is "N":
As of now, query flags are unused

2017-10-19 16:34 UTC, jurrdb approved these changes

2017-10-19 16:34 UTC, merged